### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by 0xlethe** [0xlethe/react-native-media-control#1]
- [ ] full screen with Landscape & Portrait
- [ ] control (Play, pause, stop)
- [ ] repeat playback
- [ ] background play
- [ ] background play control
